# Site
name: "Alberto Fernández-Capel"
description: "Personal Blog"
meta_description: "Alberto Fernández-Capel Personal Website"
logo: 'assets/images/afcapel.svg'
baseurl:
google_analytics: 'UA-106537463-2'

# Authors
authors:
  alberto:
    name: Alberto
    display_name: Alberto
    gravatar: ec109e50efa17647903b7f31eee1c458
    email: afcapel@gmail.com
    web: https://www.afcapel.com
    twitter: https://twitter.com/afcapel
    description: "I build software"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
